/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AcademyAcademyRouteRouteImport } from './routes/_academy/academy.route'
import { Route as StudentStudentRouteRouteImport } from './routes/_student/student.route'
import { Route as AcademyAcademyIndexRouteImport } from './routes/_academy/academy.index'
import { Route as AcademyAcademyBillingRouteImport } from './routes/_academy/academy.billing'
import { Route as AcademyAcademyCoursesRouteImport } from './routes/_academy/academy.courses'
import { Route as AcademyAcademyResultsRouteImport } from './routes/_academy/academy.results'
import { Route as AcademyAcademySettingsRouteImport } from './routes/_academy/academy.settings'
import { Route as AcademyAcademyStudentsRouteImport } from './routes/_academy/academy.students'
import { Route as AcademyAcademyTestsRouteImport } from './routes/_academy/academy.tests'
import { Route as AuthAcademyLoginRouteImport } from './routes/_auth/academy.login'
import { Route as AuthAcademySignupRouteImport } from './routes/_auth/academy.signup'
import { Route as AuthStudentLoginRouteImport } from './routes/_auth/student.login'
import { Route as StudentStudentIndexRouteImport } from './routes/_student/student.index'
import { Route as StudentStudentResultsRouteImport } from './routes/_student/student.results'
import { Route as StudentStudentSettingsRouteImport } from './routes/_student/student.settings'
import { Route as StudentStudentTestsRouteImport } from './routes/_student/student.tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAcademyRouteRoute = AcademyAcademyRouteRouteImport.update({
  id: '/_academy/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentRouteRoute = StudentStudentRouteRouteImport.update({
  id: '/_student/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAcademyIndexRoute = AcademyAcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AcademyAcademyBillingRoute = AcademyAcademyBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AcademyAcademyCoursesRoute = AcademyAcademyCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AcademyAcademyResultsRoute = AcademyAcademyResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AcademyAcademySettingsRoute = AcademyAcademySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AcademyAcademyStudentsRoute = AcademyAcademyStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AcademyAcademyTestsRoute = AcademyAcademyTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AcademyAcademyRouteRoute,
} as any)
const AuthAcademyLoginRoute = AuthAcademyLoginRouteImport.update({
  id: '/academy/login',
  path: '/academy/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAcademySignupRoute = AuthAcademySignupRouteImport.update({
  id: '/academy/signup',
  path: '/academy/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentLoginRoute = AuthStudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const StudentStudentIndexRoute = StudentStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentResultsRoute = StudentStudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentSettingsRoute = StudentStudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentTestsRoute = StudentStudentTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyAcademyRouteRouteWithChildren
  '/student': typeof StudentStudentRouteRouteWithChildren
  '/academy/billing': typeof AcademyAcademyBillingRoute
  '/academy/courses': typeof AcademyAcademyCoursesRoute
  '/academy/results': typeof AcademyAcademyResultsRoute
  '/academy/settings': typeof AcademyAcademySettingsRoute
  '/academy/students': typeof AcademyAcademyStudentsRoute
  '/academy/tests': typeof AcademyAcademyTestsRoute
  '/academy/login': typeof AuthAcademyLoginRoute
  '/academy/signup': typeof AuthAcademySignupRoute
  '/student/login': typeof AuthStudentLoginRoute
  '/student/results': typeof StudentStudentResultsRoute
  '/student/settings': typeof StudentStudentSettingsRoute
  '/student/tests': typeof StudentStudentTestsRoute
  '/academy/': typeof AcademyAcademyIndexRoute
  '/student/': typeof StudentStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy/billing': typeof AcademyAcademyBillingRoute
  '/academy/courses': typeof AcademyAcademyCoursesRoute
  '/academy/results': typeof AcademyAcademyResultsRoute
  '/academy/settings': typeof AcademyAcademySettingsRoute
  '/academy/students': typeof AcademyAcademyStudentsRoute
  '/academy/tests': typeof AcademyAcademyTestsRoute
  '/academy/login': typeof AuthAcademyLoginRoute
  '/academy/signup': typeof AuthAcademySignupRoute
  '/student/login': typeof AuthStudentLoginRoute
  '/student/results': typeof StudentStudentResultsRoute
  '/student/settings': typeof StudentStudentSettingsRoute
  '/student/tests': typeof StudentStudentTestsRoute
  '/academy': typeof AcademyAcademyIndexRoute
  '/student': typeof StudentStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_academy/academy': typeof AcademyAcademyRouteRouteWithChildren
  '/_student/student': typeof StudentStudentRouteRouteWithChildren
  '/_academy/academy/billing': typeof AcademyAcademyBillingRoute
  '/_academy/academy/courses': typeof AcademyAcademyCoursesRoute
  '/_academy/academy/results': typeof AcademyAcademyResultsRoute
  '/_academy/academy/settings': typeof AcademyAcademySettingsRoute
  '/_academy/academy/students': typeof AcademyAcademyStudentsRoute
  '/_academy/academy/tests': typeof AcademyAcademyTestsRoute
  '/_auth/academy/login': typeof AuthAcademyLoginRoute
  '/_auth/academy/signup': typeof AuthAcademySignupRoute
  '/_auth/student/login': typeof AuthStudentLoginRoute
  '/_student/student/results': typeof StudentStudentResultsRoute
  '/_student/student/settings': typeof StudentStudentSettingsRoute
  '/_student/student/tests': typeof StudentStudentTestsRoute
  '/_academy/academy/': typeof AcademyAcademyIndexRoute
  '/_student/student/': typeof StudentStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/student'
    | '/academy/billing'
    | '/academy/courses'
    | '/academy/results'
    | '/academy/settings'
    | '/academy/students'
    | '/academy/tests'
    | '/academy/login'
    | '/academy/signup'
    | '/student/login'
    | '/student/results'
    | '/student/settings'
    | '/student/tests'
    | '/academy/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy/billing'
    | '/academy/courses'
    | '/academy/results'
    | '/academy/settings'
    | '/academy/students'
    | '/academy/tests'
    | '/academy/login'
    | '/academy/signup'
    | '/student/login'
    | '/student/results'
    | '/student/settings'
    | '/student/tests'
    | '/academy'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_academy/academy'
    | '/_student/student'
    | '/_academy/academy/billing'
    | '/_academy/academy/courses'
    | '/_academy/academy/results'
    | '/_academy/academy/settings'
    | '/_academy/academy/students'
    | '/_academy/academy/tests'
    | '/_auth/academy/login'
    | '/_auth/academy/signup'
    | '/_auth/student/login'
    | '/_student/student/results'
    | '/_student/student/settings'
    | '/_student/student/tests'
    | '/_academy/academy/'
    | '/_student/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcademyAcademyRouteRoute: typeof AcademyAcademyRouteRouteWithChildren
  StudentStudentRouteRoute: typeof StudentStudentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_academy/academy': {
      id: '/_academy/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyAcademyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student': {
      id: '/_student/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentStudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_academy/academy/': {
      id: '/_academy/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyAcademyIndexRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_academy/academy/billing': {
      id: '/_academy/academy/billing'
      path: '/billing'
      fullPath: '/academy/billing'
      preLoaderRoute: typeof AcademyAcademyBillingRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_academy/academy/courses': {
      id: '/_academy/academy/courses'
      path: '/courses'
      fullPath: '/academy/courses'
      preLoaderRoute: typeof AcademyAcademyCoursesRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_academy/academy/results': {
      id: '/_academy/academy/results'
      path: '/results'
      fullPath: '/academy/results'
      preLoaderRoute: typeof AcademyAcademyResultsRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_academy/academy/settings': {
      id: '/_academy/academy/settings'
      path: '/settings'
      fullPath: '/academy/settings'
      preLoaderRoute: typeof AcademyAcademySettingsRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_academy/academy/students': {
      id: '/_academy/academy/students'
      path: '/students'
      fullPath: '/academy/students'
      preLoaderRoute: typeof AcademyAcademyStudentsRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_academy/academy/tests': {
      id: '/_academy/academy/tests'
      path: '/tests'
      fullPath: '/academy/tests'
      preLoaderRoute: typeof AcademyAcademyTestsRouteImport
      parentRoute: typeof AcademyAcademyRouteRoute
    }
    '/_auth/academy/login': {
      id: '/_auth/academy/login'
      path: '/academy/login'
      fullPath: '/academy/login'
      preLoaderRoute: typeof AuthAcademyLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/academy/signup': {
      id: '/_auth/academy/signup'
      path: '/academy/signup'
      fullPath: '/academy/signup'
      preLoaderRoute: typeof AuthAcademySignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/student/login': {
      id: '/_auth/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof AuthStudentLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_student/student/': {
      id: '/_student/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentStudentIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/_student/student/results': {
      id: '/_student/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentStudentResultsRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/_student/student/settings': {
      id: '/_student/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentStudentSettingsRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/_student/student/tests': {
      id: '/_student/student/tests'
      path: '/tests'
      fullPath: '/student/tests'
      preLoaderRoute: typeof StudentStudentTestsRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAcademyLoginRoute: typeof AuthAcademyLoginRoute
  AuthAcademySignupRoute: typeof AuthAcademySignupRoute
  AuthStudentLoginRoute: typeof AuthStudentLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAcademyLoginRoute: AuthAcademyLoginRoute,
  AuthAcademySignupRoute: AuthAcademySignupRoute,
  AuthStudentLoginRoute: AuthStudentLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AcademyAcademyRouteRouteChildren {
  AcademyAcademyBillingRoute: typeof AcademyAcademyBillingRoute
  AcademyAcademyCoursesRoute: typeof AcademyAcademyCoursesRoute
  AcademyAcademyResultsRoute: typeof AcademyAcademyResultsRoute
  AcademyAcademySettingsRoute: typeof AcademyAcademySettingsRoute
  AcademyAcademyStudentsRoute: typeof AcademyAcademyStudentsRoute
  AcademyAcademyTestsRoute: typeof AcademyAcademyTestsRoute
  AcademyAcademyIndexRoute: typeof AcademyAcademyIndexRoute
}

const AcademyAcademyRouteRouteChildren: AcademyAcademyRouteRouteChildren = {
  AcademyAcademyBillingRoute: AcademyAcademyBillingRoute,
  AcademyAcademyCoursesRoute: AcademyAcademyCoursesRoute,
  AcademyAcademyResultsRoute: AcademyAcademyResultsRoute,
  AcademyAcademySettingsRoute: AcademyAcademySettingsRoute,
  AcademyAcademyStudentsRoute: AcademyAcademyStudentsRoute,
  AcademyAcademyTestsRoute: AcademyAcademyTestsRoute,
  AcademyAcademyIndexRoute: AcademyAcademyIndexRoute,
}

const AcademyAcademyRouteRouteWithChildren =
  AcademyAcademyRouteRoute._addFileChildren(AcademyAcademyRouteRouteChildren)

interface StudentStudentRouteRouteChildren {
  StudentStudentResultsRoute: typeof StudentStudentResultsRoute
  StudentStudentSettingsRoute: typeof StudentStudentSettingsRoute
  StudentStudentTestsRoute: typeof StudentStudentTestsRoute
  StudentStudentIndexRoute: typeof StudentStudentIndexRoute
}

const StudentStudentRouteRouteChildren: StudentStudentRouteRouteChildren = {
  StudentStudentResultsRoute: StudentStudentResultsRoute,
  StudentStudentSettingsRoute: StudentStudentSettingsRoute,
  StudentStudentTestsRoute: StudentStudentTestsRoute,
  StudentStudentIndexRoute: StudentStudentIndexRoute,
}

const StudentStudentRouteRouteWithChildren =
  StudentStudentRouteRoute._addFileChildren(StudentStudentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcademyAcademyRouteRoute: AcademyAcademyRouteRouteWithChildren,
  StudentStudentRouteRoute: StudentStudentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
